### ISSUE TITLE
[Question] Versioning and branching model

### ISSUE THREAD

**Issue by lukas-vlcek** [sematext/elasticsearch-field-stats#2]
Hello from [_other ES plugin_](https://github.com/vvanholl/elasticsearch-prometheus-exporter) here, we are currently in the process of migrating to different branching and versioning model to support bug-fixing and feature back-porting and I was interested in how you are doing it here. I noticed that you started with branches on the `MAJOR.MINOR` level and doing releases at the `MAJOR.MINOR.PATCH` level. (I guess this is what you inherited from Elasticsearch repo directly?)

Have you considered going one level deeper? In other words, if you realize you need to fix already released plugin for say Elasticsearch version 6.5.0, or you will want to back-port some features to older releases, how are you going to do it?

We are currently investigating this topic and various reasonings behind this here: 
https://github.com/vvanholl/elasticsearch-prometheus-exporter/issues/139

I would love to hear your feedback on this.

Cheers!
Lukáš

**Comment by prog8** [comment]
Hi Lukáš,
Field stats plugin is a bit specific case. Its logic is strongly stuck to ES and Lucene internal APIs and there is not much to change there. Field stats API is not evolving. It only reflects what an old API had ... at least today. We want to stick plugin version to ES versions but we'll see if this will be possible in a long run. As you know ES plugins have to follow ES version (otherwise plugin is rejected by ES during installation).

We didn't plan to add another level in version numbers. We're not saying we will not have to use such an approach. If there are bugs in a plugin which have to be fixed quickly (without bumping the version of ES) there will probably no other choice than changing the versioning model. You can find a similar approach (to the one you suggested) in Jörg Prante's ES plugins bundle https://github.com/jprante/elasticsearch-plugin-bundle. Even though this project doesn't seem to be maintained any longer but you can see that for the older version of ES Jörg used the same versioning as you suggested.

I hope this helps you make a decision about versioning in ES Prometheus exporter.

Paweł
